slipstream/SlipStreamWebUI

pom.xml
=> fix dependency type

resources/index.html
=> fix insecure script

build.boot, resources/index.html, src/cljs/sixsq/slipstream/webui.cljs, src/cljs/sixsq/slipstream/webui/main/events.cljs, src/cljs/sixsq/slipstream/webui/utils.cljs
=> detect the host url by default

src/cljs/sixsq/slipstream/webui/activity/views.cljs, src/cljs/sixsq/slipstream/webui/apps/views.cljs, src/cljs/sixsq/slipstream/webui/authn/views.cljs, src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs, src/cljs/sixsq/slipstream/webui/i18n/events.cljs, src/cljs/sixsq/slipstream/webui/i18n/subs.cljs, src/cljs/sixsq/slipstream/webui/i18n/views.cljs, src/cljs/sixsq/slipstream/webui/main/db.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/offers/views.cljs
=> localize the interface widgets

src/cljs/sixsq/slipstream/webui.cljs, src/cljs/sixsq/slipstream/webui/main/effects.cljs, src/cljs/sixsq/slipstream/webui/panel/authn/effects.cljs, src/cljs/sixsq/slipstream/webui/widget/history/utils.cljs
=> switch to using timbre

src/cljs/sixsq/slipstream/webui/main/db.cljs, src/cljs/sixsq/slipstream/webui/panel/deployment/subs.cljs, src/cljs/sixsq/slipstream/webui/panel/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/widget/i18n/dictionary.cljs
=> fix atom states for run controls

build.boot
Connected to SixSq/tasklist#1251.
=> update cljs dependencies

build.boot, resources/authn/index.html, resources/webui/index.html, src/cljs/sixsq/slipstream/webui/main/views.cljs
=> use dynamically generated version in footers

src/cljs/sixsq/slipstream/webui/db.cljs
=> allow the group to be nil

resources/authn/index.html
=> add missing modals and alerts for password reset

build.boot, src/cljs/sixsq/slipstream/authn.cljs, src/cljs/sixsq/slipstream/webui.cljs, src/cljs/sixsq/slipstream/webui/defines.cljs
Reorganize the defines to avoid warnings when compiling the authn and webui applications.
=> reorganize defines

src/cljs/sixsq/slipstream/authn/main/subs.cljs, src/cljs/sixsq/slipstream/authn/main/views.cljs, src/cljs/sixsq/slipstream/webui/panel/authn/views_forms.cljs
=> render error messages; prefer group label for login button

src/cljs/sixsq/slipstream/webui/main/subs.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs
=> pass query parameters through to error message

build.boot, src/clj/sixsq/slipstream/webui/styles.clj
=> add garden css compiler

src/cljs/sixsq/slipstream/webui/panel/authn/views_forms.cljs
=> switch back to only using labels in the login buttons

src/cljs/sixsq/slipstream/webui/panel/app/effects.cljs, src/cljs/sixsq/slipstream/webui/panel/app/views.cljs
Provide rendering of app metadata as well as providing a list of children.
=> add more app rendering

src/cljs/sixsq/slipstream/webui/db.cljs, src/cljs/sixsq/slipstream/webui/main/cimi_effects.cljs, src/cljs/sixsq/slipstream/webui/main/events.cljs, src/cljs/sixsq/slipstream/webui/panel/app/effects.cljs, src/cljs/sixsq/slipstream/webui/panel/app/events.cljs, src/cljs/sixsq/slipstream/webui/panel/authn/utils.cljs, src/cljs/sixsq/slipstream/webui/panel/cimi/utils.cljs, src/cljs/sixsq/slipstream/webui/panel/credential/utils.cljs, src/cljs/sixsq/slipstream/webui/panel/deployment/effects.cljs, src/cljs/sixsq/slipstream/webui/panel/deployment/events.cljs
Connected to slipstream/SlipStreamClojureAPI#85
=> update for changes in api

src/cljs/sixsq/slipstream/webui/panel/app/effects.cljs, src/cljs/sixsq/slipstream/webui/panel/deployment/views.cljs
=> updates for changes in clojurescript API

pom.xml, project.clj
Connected to slipstream/SlipStreamClojureAPI#96
=> rename clojure client artifact

resources/public/css/webui.css, src/cljs/sixsq/slipstream/webui/application/views.cljs, src/cljs/sixsq/slipstream/webui/authn/views.cljs, src/cljs/sixsq/slipstream/webui/cimi/events.cljs, src/cljs/sixsq/slipstream/webui/cimi/utils.cljs, src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/cimi_api/utils.cljs, src/cljs/sixsq/slipstream/webui/cimi_detail/events.cljs, src/cljs/sixsq/slipstream/webui/cimi_detail/spec.cljs, src/cljs/sixsq/slipstream/webui/cimi_detail/subs.cljs, src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs, src/cljs/sixsq/slipstream/webui/dashboard/views.cljs, src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/editor/editor.cljs, src/cljs/sixsq/slipstream/webui/main/events.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/panel.cljs, src/cljs/sixsq/slipstream/webui/profile/views.cljs, src/cljs/sixsq/slipstream/webui/settings/views.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs, src/cljs/sixsq/slipstream/webui/utils/form_fields.cljs, src/cljs/sixsq/slipstream/webui/utils/forms.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs, src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs, src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Connected to #90 
Connected to #91 
Connected to #93
=> Resource with template href

src/cljs/sixsq/slipstream/webui/application/effects.cljs, src/cljs/sixsq/slipstream/webui/application/views.cljs, src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
Minimal implementation to make the applications navigable.
=> add application navigation

src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs, src/cljs/sixsq/slipstream/webui/main/subs.cljs, src/cljs/sixsq/slipstream/webui/profile/views.cljs, src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs, src/cljs/sixsq/slipstream/webui/utils/values.cljs
Does a simple rendering of href maps as links to the appropriate CIMI detail page.  Same for lists of href maps.
=> render hrefs as links

project.clj, resources/public/webui.html, src/cljs/sixsq/slipstream/webui/cimi_api/effects.cljs, src/cljs/sixsq/slipstream/webui/db/spec.cljs, src/cljs/sixsq/slipstream/webui/editor/editor.cljs, src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/metrics/events.cljs, src/cljs/sixsq/slipstream/webui/metrics/spec.cljs, src/cljs/sixsq/slipstream/webui/metrics/subs.cljs, src/cljs/sixsq/slipstream/webui/metrics/utils.cljs, src/cljs/sixsq/slipstream/webui/metrics/views.cljs, src/cljs/sixsq/slipstream/webui/plot/effects.cljs, src/cljs/sixsq/slipstream/webui/plot/events.cljs, src/cljs/sixsq/slipstream/webui/plot/plot.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs
Initial attempt to add plotting capabilities to the UI.
=> add plots of metrics

src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs
=> avoid duplicate keys in operation buttons when data contains :key

src/cljs/sixsq/slipstream/webui/cimi_detail/views.cljs
=> ensure editor is rendered only with valid data

project.clj
Connected to slipstream/SlipStreamClojureAPI#100
=> switch from phantomjs to nashorn

src/cljs/sixsq/slipstream/webui/utils/form_fields.cljs
=> add support for href entry

src/cljs/sixsq/slipstream/webui/main/views.cljs
The metrics view is broken (not available).  Fix this.
=> metrics view broken

src/cljs/sixsq/slipstream/webui/authn/views.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/profile/views.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs
=> avoid issues related to long usernames

src/cljs/sixsq/slipstream/webui/editor/editor.cljs, src/cljs/sixsq/slipstream/webui/plot/plot.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs
Remove unused XML utilities.  Refactor others to make implementation/names clearer.
=> remove xml utils; refactor others

src/cljs/sixsq/slipstream/webui/authn/views.cljs
=> separate dropdown and login button

src/cljs/sixsq/slipstream/webui/cimi/views.cljs
Provide simple formatting for aggregation results.
=> format aggregations

pom.xml, src/cljs/sixsq/slipstream/webui/metrics/views.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs, test/cljs/sixsq/slipstream/webui/core_test.cljs, test/cljs/sixsq/slipstream/webui/runner.cljs, test/cljs/sixsq/slipstream/webui/utils/general_test.cljs
fix random-id utility that caused metric plots to fail
=> fix metric plots

src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs
=> Issue #142 placeholders submit request on enter

src/cljs/sixsq/slipstream/webui/utils/time.cljs
Connected to slipstream/SlipStreamServer#1504.
=> change date format in session

src/cljs/sixsq/slipstream/webui/usage/effects.cljs, src/cljs/sixsq/slipstream/webui/usage/events.cljs, src/cljs/sixsq/slipstream/webui/usage/spec.cljs, src/cljs/sixsq/slipstream/webui/usage/subs.cljs, src/cljs/sixsq/slipstream/webui/usage/utils.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs
=> refactor usage code; fix problem when default date range is nil

src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs, src/cljs/sixsq/slipstream/webui/utils/forms.cljs
=> refactor key press handling

src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
=> reports not shown in standard UI

resources/public/css/webui.css, src/cljs/sixsq/slipstream/webui/application/views.cljs, src/cljs/sixsq/slipstream/webui/i18n/views.cljs, src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
=> replace menu by semanticui sidebar

src/cljs/sixsq/slipstream/webui/acl/views.cljs, src/cljs/sixsq/slipstream/webui/application/views.cljs, src/cljs/sixsq/slipstream/webui/authn/views.cljs, src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs, src/cljs/sixsq/slipstream/webui/legacy_application/views.cljs, src/cljs/sixsq/slipstream/webui/messages/views.cljs, src/cljs/sixsq/slipstream/webui/metrics/views.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs, src/cljs/sixsq/slipstream/webui/profile/views.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs, src/cljs/sixsq/slipstream/webui/utils/collapsible_card.cljs, src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs, src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs, src/cljs/sixsq/slipstream/webui/utils/style.cljs
Update the controls and styles for consistency.  Must be refined further before the next release.
=> update controls and styles for consistency

src/cljs/sixsq/slipstream/webui/cimi/events.cljs, src/cljs/sixsq/slipstream/webui/cimi/views.cljs
=> provide message for an unknown resource

src/cljs/sixsq/slipstream/webui/cimi/views.cljs
=> add on-close handler

src/cljs/sixsq/slipstream/webui/profile/views.cljs, src/cljs/sixsq/slipstream/webui/utils/resource_details.cljs, src/cljs/sixsq/slipstream/webui/utils/values.cljs
=> format raw vector values

src/cljs/sixsq/slipstream/webui/cimi/events.cljs
=> do not send message on uninitialized cep

resources/public/webui.html, src/cljs/sixsq/slipstream/webui/authn/views.cljs, src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/main/effects.cljs
Some improvements have been made the WebUI to address issues identified by the Chrome inspector audit facility.  The page scores quite well on performance, best practices, and SEO.  The main area for improvement is in accessibility.  See the attached screenshot.
=> improve best practices with webui

src/cljs/sixsq/slipstream/webui/usage/utils.cljs
=> remove storage metering from queries

src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs
Connected to slipstream/SlipStreamUI#791
=> fix broken trash icon

src/cljs/sixsq/slipstream/webui/dashboard/views.cljs
Connected to slipstream/SlipStreamUI#791.
=> use active tab control

src/cljs/sixsq/slipstream/webui/usage/views.cljs
=> use credential name in list, if available

resources/public/css/webui.css
=> allow input field to capture focus in search dropdown

src/cljs/sixsq/slipstream/webui/deployment/spec.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs, src/cljs/sixsq/slipstream/webui/usage/spec.cljs
=> have filter open by default

src/cljs/sixsq/slipstream/webui/cimi/events.cljs, src/cljs/sixsq/slipstream/webui/cimi/spec.cljs, src/cljs/sixsq/slipstream/webui/cimi/subs.cljs, src/cljs/sixsq/slipstream/webui/cimi/views.cljs, src/cljs/sixsq/slipstream/webui/deployment/events.cljs, src/cljs/sixsq/slipstream/webui/deployment/spec.cljs, src/cljs/sixsq/slipstream/webui/deployment/subs.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/subs.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs, src/cljs/sixsq/slipstream/webui/usage/events.cljs, src/cljs/sixsq/slipstream/webui/usage/spec.cljs, src/cljs/sixsq/slipstream/webui/usage/subs.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs
=> filter always open

src/cljs/sixsq/slipstream/webui/usage/effects.cljs, src/cljs/sixsq/slipstream/webui/usage/events.cljs, src/cljs/sixsq/slipstream/webui/usage/spec.cljs, src/cljs/sixsq/slipstream/webui/usage/subs.cljs, src/cljs/sixsq/slipstream/webui/usage/utils.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs
=> remove totals from usage table

src/cljs/sixsq/slipstream/webui/dashboard/views_deployments.cljs, src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs
=> change sliders to toggles

src/cljs/sixsq/slipstream/webui/usage/utils.cljs, src/cljs/sixsq/slipstream/webui/usage/views.cljs, src/cljs/sixsq/slipstream/webui/utils/time.cljs
=> do not disable date pickers

src/cljs/sixsq/slipstream/webui/usage/utils.cljs
Connected to https://github.com/slipstream/SlipStreamWebUI/issues/198
=> Change the billable filter to use the billable attribute

src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs
Connected to #233 
Connected to #164
=> nuvlabox auto refresh state and add colors for state

src/cljs/sixsq/slipstream/webui/metrics/spec.cljs, src/cljs/sixsq/slipstream/webui/metrics/views.cljs, src/cljs/sixsq/slipstream/webui/plot/plot.cljs
ugliness at the very first load because no data from metrics yet
=> update with animation working

src/cljs/sixsq/slipstream/webui/dashboard/events.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/effects.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/events.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/spec.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/subs.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/utils.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox/views.cljs, src/cljs/sixsq/slipstream/webui/quota/views.cljs, src/cljs/sixsq/slipstream/webui/utils/general.cljs
=> paging added for nuvlaboxes

project.clj, src/cljs/sixsq/slipstream/webui/main/views.cljs, src/cljs/sixsq/slipstream/webui/main/views_sidebar.cljs, src/cljs/sixsq/slipstream/webui/metrics/views.cljs, src/cljs/sixsq/slipstream/webui/nuvlabox_detail/views.cljs, src/cljs/sixsq/slipstream/webui/plot/plot.cljs, src/cljs/sixsq/slipstream/webui/utils/semantic_ui.cljs
=> replace chartjs with react chartjs which is react ready

src/cljs/sixsq/slipstream/webui/authn/views.cljs
=> make reset password modal id consistent with others; fix formatting

src/cljs/sixsq/slipstream/webui/core.cljs
=> trigger rendering of reset password modal

package.json, project.clj
Connected to #292 
Connected to #291.
=> upgrade shadow-cljs, clojurescript, and secretary

src/cljs/sixsq/slipstream/webui/data/effects.cljs, src/cljs/sixsq/slipstream/webui/data/events.cljs, src/cljs/sixsq/slipstream/webui/data/spec.cljs, src/cljs/sixsq/slipstream/webui/data/views.cljs
Connected to SixSq/tasklist#1777
=> implement full text search for data page

src/cljs/sixsq/slipstream/webui/data/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/spec.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/subs.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views_credentials.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views_data.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views_parameters.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views_size.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/views_summary.cljs
Refactor code and refine layout with table for summary.
Connected to SixSq/tasklist#1774.
=> refine deployment dialog

src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/deployment_detail/utils.cljs, src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
Connected to SixSq/tasklist#1792.
=> add corner delete button

src/cljs/sixsq/slipstream/webui/deployment_dialog/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs
=> minimal change to respect schema

src/cljs/sixsq/slipstream/webui/deployment_detail/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_detail/views.cljs
Connected to slipstream/SlipStreamServer#1747
=> use href instead of javascript for downloading report

src/cljs/sixsq/slipstream/webui/deployment_dialog/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs
Connected to slipstream/SlipStreamServer#1745. 
Use keywords for keys in serviceOffers in deployment.
=> service offer keywords

src/cljs/sixsq/slipstream/webui/data/effects.cljs, src/cljs/sixsq/slipstream/webui/data/events.cljs, src/cljs/sixsq/slipstream/webui/data/spec.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/events.cljs, src/cljs/sixsq/slipstream/webui/deployment_dialog/utils.cljs
Connected to https://github.com/slipstream/SlipStreamWebUI/issues/323
Connected to slipstream/SlipStreamServer#1745
=> Provide dataset id as string in service offer map

src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
Connected to SixSq/tasklist#1796
=> confirmation message before stoping or deleting deployment

src/cljs/sixsq/slipstream/webui/deployment/views.cljs, src/cljs/sixsq/slipstream/webui/i18n/dictionary.cljs
=> change deployment card link
